### ISSUE TITLE
TODO: Remaining Tasks

### ISSUE THREAD

**Issue by wam82** [wam82/OpenGLCarShowcase#4]
- [x] Handle multiple lights in shaders (Not in scope)
- [x] Implement a function to turn on/off vehicle lights (Not in scope)
- [x] Implement a function to switch between preset colors
- [x] Implement a function to switch between preset paint finishes
- [x] Add engine to model
